---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zues865/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp spark.php $DEPLOYPATH
    - /bin/cp phpunit.xml.dist $DEPLOYPATH
